### ISSUE TITLE
Update kodi-tegra fork to Kodi 19.x "Matrix" Alpha 2 commits

### ISSUE THREAD

**Issue by Hedda** [aliubimov/xbmc#5]
@aliubimov please consider updating your kodi-tegra for to newly announced Kodi 19.x "Matrix" Alpha 2 pre-release version:

https://kodi.tv/article/kodi-19x-matrix-alpha-2

19.0a2-Matrix tag release

https://github.com/xbmc/xbmc/tree/19.0a2-Matrix

https://github.com/xbmc/xbmc/compare/19.0a1-Matrix...19.0a2-Matrix

This is a request for your kodi-tegra fork in https://github.com/aliubimov/xbmc/tree/feature/kodi-tegra

I think that you will probably find more people interested in your kodi-tegra now that the 2GB Nvidia Jetson Nano is available.

https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-nano/education-projects/

https://developer.nvidia.com/embedded/jetson-nano-2gb-developer-kit

**Comment by aliubimov** [comment]
Oh wow, I haven't realize there is interest to my work :) Will do, thanks for heads up. I recently lost my ARM build server, have to restore it, before I can build new releases.

**Comment by Hedda** [comment]
> Oh wow, I haven't realize there is interest to my work :) Will do, thanks for heads up. 

Yes I believe so, especially now because of the newly announced "2GB" NVIDIA Jetson Nano Developer Kit which cost a lot less.

I think that pull requests for Tegra Decoder and L4T hardware decoding to upstream 'xbmc/xbmc' would be much welcomed!

https://github.com/aliubimov/xbmc/commits/feature/kodi-tegra -> https://github.com/xbmc/xbmc

Please also consider joining the Kodi community forums and posting your progress in both of these two forums threads here:

https://forum.kodi.tv/showthread.php?tid=357522

https://forum.kodi.tv/showthread.php?tid=342261

> I recently lost my ARM build server, have to restore it, before I can build new releases.

@aliubimov Nice! FYI, the Kodi team have just yesterday also announced a Kodi 19.x "Matrix" Alpha 3 pre-release version as well:

https://kodi.tv/article/kodi-19x-matrix-alpha-3

https://github.com/xbmc/xbmc/tree/19.0a3-Matrix

https://github.com/xbmc/xbmc/compare/19.0a1-Matrix...19.0a3-Matrix

**Comment by Hedda** [comment]
By the way, would be great if Nvidia Tegra decoding could be tested with LibreELEC on an NVIDIA Jetson Nano Developer Kit 

https://libreelec.tv

It is the semi-official JeOS (Just Enough Operating System) for Kodi and many on Team Kodi are also on Team LibreELEC

**Comment by Hedda** [comment]
FYI, Kodi 19.x "Matrix" Beta 1 was just released a couple of days ago so they should only marge bug-fixes from now until final:

https://kodi.tv/article/kodi-19x-matrix-beta-1

https://github.com/xbmc/xbmc/tree/19.0b1-Matrix

https://github.com/xbmc/xbmc/compare/19.0a1-Matrix...19.0b1-Matrix

Of course, once that Kodi 19.0 "Matrix" Final version is released they will use their master branch as pre-alpha for Kodi 20.x "N".

**Comment by wodgey** [comment]
commenting here, so I get notifications! 
I have recently purchased a 4gb Nano dev-kit variant and very eager to have a kodi fork that works. 
although, I have no idea how to compile it! lol. 
I tried compiling the master fork, from their documentation but failed on compiling one of the dependencies (one of the wayland things). this was only 30 mins ago thlough, so I will keep reading/researching.
really glad there's a fork with support for these devices though

edit2add
ok, I am clearly out of my depth here. I've not done any programming since my college days, using assembly on 6502 cpu's and I don;t have the faintest idea how to compile for object oriented languages. I shall have to wait for more insight :(

I still appreciate the glimmer of hope that I can have a working install of kodi on my device though

**Comment by aliubimov** [comment]
There is Docker container that is already precompiled for Jetson. Check it out https://hub.docker.com/r/aliubimov/kodi-tegra

**Comment by wodgey** [comment]
I will indeed check it out.. I've gotten further with my own learning on compilation though. Now I'm bashing my head against missing (dependencies?) Features, such as nfs and plist (being the first two in the list that I remember). They won't cmake though using the same format as in the kodi guide, so I'll try your docker instead.
I've never used docker before but I understand that it's like a mini virtual environment but not as heavy\clunky as a full vm.
I'm curious if I could pull the binaries out from the container to run on the native host but I'm looking forward to playing around.

Edit 2 add
I've tried to start the container using the instructions on the docker web page but it doesn't start. This is after I've performed some apt updates\upgrade though so I've re-flashed my sd card(s) and will try again (I've got a virgin r32.4 flashed to a 32gb sd card and also have a 128 gig card with "retropie on the nano" image from techtoytinker)

edit 2 add again (a few minutes after posting but several hours after typing. I forgot to click "post"! lol)
it works on my ROTN install so I assume that it works too on my r32.4 install as well. I have started watching some 4k content from my NAS and playback was smooth and glitchless! nice!
HOWEVER, my xbox one (wired only, haven;t checked wireless) controller doesn;t work within kodi, so I assume i would need to somehow install the peripheral.joystick (or whatever it is called) within the container. Also, if not already, perhaps either xpad or xboxdrv.
I have not even looked yet, at placing the kodi (and x11 & xrandr) binaries into the host filesystem yet as I am in the middle of boring life activities (like making dinner and also doing washing)

**Comment by Tiemichael** [comment]
Thanks for providing this!
I have successfully installed Kodi on my Nano running Ubuntu20.04.

@aliubimov: are you going to maintain both this version as well as the Docker-version?

Looking forward to some update once in a while

**Comment by Hedda** [comment]
> @aliubimov: are you going to maintain both this version as well as the Docker-version?

Suggest best option would be if @aliubimov could try to get it submitted and merged upstream to Kodi's 'xbmc/xbmc' repo:

https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md

https://github.com/xbmc/xbmc/

It will always be much harder and more work to try to maintain something downstream in the long run.

Personally, I think that it can get it to be merged upstream then you will eventually get more developers eyes and input on it.

Niche scene but I believe especially emulation gamers will find Jetson GPUs useful with RetroPlayer/Libretro games in Kodi.

**Comment by Hedda** [comment]
> HOWEVER, my xbox one (wired only, haven;t checked wireless) controller doesn;t work within kodi, so I assume i would need to somehow install the peripheral.joystick (or whatever it is called) within the container. Also, if not already, perhaps either xpad or xboxdrv.

**Comment by aliubimov** [comment]
Yes, I am maintaining both versions. Will create PR, once I address few things. It is not yet _merge friendly_, per say.
