### ISSUE TITLE
Fails to work on Nintendo Switch

### ISSUE THREAD

**Issue by theofficialgman** [aliubimov/xbmc#8]
## Hardware
 - NVIDIA Jetson UNKNOWN
   * Jetpack 4.3 [L4T 32.3.1]
   * NV Power Mode: Locked_MAX - Type: 7
   * jetson_stats.service: active
 - Board info:
   * Type: UNKNOWN
   * SOC Family: tegra210 - ID:33
   * Module: UNKNOWN - Board: UNKNOWN
   * Code Name: icosa
   * Boardids: 2595:0000:A0
   * CUDA GPU architecture (ARCH_BIN): NONE
   * Serial Number: 1234
 - Libraries:
   * CUDA: NOT_INSTALLED
   * cuDNN: 7.6.3.28
   * TensorRT: 6.0.1.10
   * Visionworks: NOT_INSTALLED
   * OpenCV: 4.1.1 compiled CUDA: NO
   * VPI: NOT_INSTALLED
   * Vulkan: 1.1.70
## Bug report
I am able to compile kodi/tegra-support with
<pre>
cmake ../kodi-tegra/xbmc -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gles -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_FLATBUFFERS=ON -DENABLE_INTERNAL_FMT=ON -DENABLE_V4L2=ON -DENABLE_NVBUFFER=ON -DENABLE_INTERNAL_SPDLOG=ON -DENABLE_VAAPI=OFF
</pre>
but when ever I attempt to launch a video within kodi, nothing ever launches and I'm stuck with the thinking circle

Here is a snippet of what the log looks like https://pastebin.com/QX9VbXWS

**Comment by aliubimov** [comment]
Looks like for some reason it is not able to map memory for video buffer.

`2020-12-14 19:11:27.875 T:10298   ERROR <general>: CNVV4LBuffer::Map failed to mmap buffer id:0 fd:1828717656 offset:0 : Bad file descriptor`

Is there anything interesting in dmesg output ?

PS: unfortunately i don't have Nintendo Switch to test it on

**Comment by theofficialgman** [comment]
I was able to build the latest tegra-support (with my PR) and CEC disabled (bug in kodi/libraries).
Unfortunatly looks like I am still running into the same/similar problem 
[kodi.log](https://github.com/aliubimov/xbmc/files/6641415/kodi.log)

Do you have any suggestions since the last time?

**Comment by theofficialgman** [comment]
also I would get a backtrace for you but when I launch kodi through gdb it makes my system hang on kodi exit...

**Comment by theofficialgman** [comment]
@aliubimov I've come back to this and built the latest commit on the feature/tegra-support branch and I am still having issues. Here is the log file for when I try to run an h264 mp4 video.
I am still using the same 32.3.1 bsp from last time.
[kodi.log](https://github.com/aliubimov/xbmc/files/7700460/kodi.log)

seems to be the same issue as last time... have you tested on 32.3.1? what jetpack have you verified this works with?

**Comment by theofficialgman** [comment]
closing as I have no need for this anymore, we have our own custom hardware accelerated ffmpeg decoders now
https://gitlab.com/switchroot/switch-l4t-multimedia/FFmpeg
